services:
  # PostgreSQL Database
  - type: pserv
    name: snapcircle-database
    plan: free

  # Backend API Service
  - type: web
    name: snapcircle-backend
    runtime: python3
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python start.py"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: snapcircle-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        sync: false
      - key: USE_S3_STORAGE
        value: true

  # Frontend Static Site
  - type: web
    name: snapcircle-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    plan: free
