databases:
  - name: snapcircle-database
    plan: free

services:
  - type: web
    name: snapcircle-backend
    env: python
    plan: free
    buildCommand: |
      cd backend

      # 1) Upgrade pip
      python -m pip install --upgrade pip

      # 2) Pre-install dlib from dlib-bin wheels (no compile)
      pip install dlib-bin==19.24.6

      # 3) Pre-install the face-recognition-models package from GitHub
      pip install git+https://github.com/ageitgey/face_recognition_models.git#egg=face-recognition-models

      # 4) Pre-install face-recognition itself, without trying to pull deps
      pip install face-recognition==1.3.0 --no-deps

      # 5) Finally, install everything else from requirements.txt as wheels only
      pip install --only-binary=:all: -r requirements.txt
    startCommand: cd backend && python start.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snapcircle-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: S3_BUCKET_NAME
        sync: false
      - key: USE_S3_STORAGE
        value: true
      - key: FRONTEND_URL
        value: https://snapcircle-frontend.onrender.com
      - key: BACKEND_URL
        value: https://snapcircle-backend.onrender.com

  - type: web
    name: snapcircle-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://snapcircle-backend.onrender.com
